---

- name: Update apt cache
  apt: update_cache=yes

- name: Download nodejs setup file
  get_url:
    url: https://deb.nodesource.com/setup_4.x
    dest: /tmp/setup_nodejs_4.x

- name: Add nodejs repo
  command: /bin/bash /tmp/setup_nodejs_4.x

- name: Install packeges
  apt:
    name: "{{ item }}"
  with_items:
    - nodejs