---

- name: Clear app directory
  file:
    path: "{{ app_dir }}"
    state: absent
    
- name: Create directory
  file:
    path: "{{ app_dir }}"
    state: directory
  
- name: Archive files
  shell: tar cvzf /tmp/app.tar.gz -C {{ workspace }} .
  delegate_to: localhost
  
- name: Unarchive files on remote server
  unarchive: src=/tmp/app.tar.gz dest={{ app_dir }}